name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: BSFishy/pip-action@v1
      with:
       packages: package
       requirements: requirements.txt
       constraints: constraints.txt
       no-deps: true
       pre: true
       editable: editable
       platform: ':all:'
       upgrade: true
       extra: extra option
    - run: python main.py
